platforms:
  - name: 微博
    weight: 0.3
  - name: 抖音
    weight: 0.25
  - name: 哔哩哔哩
    weight: 0.12
  - name: 知乎热榜
    weight: 0.1
  - name: 百度热点
    weight: 0.08
  - name: 今日头条
    weight: 0.07
  - name: 虎扑
    weight: 0.05
  - name: 豆瓣小组
    weight: 0.02
  - name: 澎湃新闻
    weight: 0.01
wechat:
  credentials:
    - appid: ""
      appsecret: ""
      author: 作者01
    - appid: ""
      appsecret: ""
      author: 作者02
    - appid: ""
      appsecret: ""
      author: 作者03
api:
  api_type: openrouter
  grok:
    key: XAI_API_KEY
    key_index: 0
    api_key:
      - ""
      - ""
    model_index: 0
    model:
      - xai/grok-2-latest
    api_base: https://api.x.ai/v1/chat/completions
  qwen:
    key: OPENAI_API_KEY
    key_index: 0
    api_key:
      - ""
      - ""
    model_index: 3
    model:
      - openai/deepseek-v3
      - openai/deepseek-r1
      - qwen-max-latest
      - openai/qwen-max
      - openai/qwen-vl-plus
      - openai/qwen-plus
    api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
  gemini:
    key: GEMINI_API_KEY
    key_index: 0
    api_key:
      - ""
      - ""
    model_index: 0
    model:
      - gemini-1.5-flash
      - gemini-1.5-pro
      - gemini-2.0-flash-lite-preview-02-05"
      - gemini-2.0-flash
    api_base: https://generativelanguage.googleapis.com
  openrouter:
    key: OPENROUTER_API_KEY
    model_index: 0
    key_index: 0
    api_key:
      - ""
      - ""
    model:
      - openrouter/deepseek/deepseek-chat-v3-0324:free
      - openrouter/deepseek/deepseek-r1:free
      - openrouter/deepseek/deepseek-chat:free
      - openrouter/qwen/qwq-32b:free
      - openrouter/google/gemini-2.0-flash-lite-preview-02-05:free
      - openrouter/google/gemini-2.0-flash-thinking-exp:free
    api_base: https://openrouter.ai/api/v1
  ollama:
    key: OPENAI_API_KEY
    model_index: 0
    key_index: 0
    api_key:
      - "tmp-key"
      - ""
    model:
      - ollama/deepseek-r1:14b
      - ollama/deepseek-r1:7b
    api_base: http://localhost:11434
img_api:
  api_type: picsum
  ali:
    api_key: ""
    model: wanx2.0-t2i-turbo
  picsum:
    api_key: ""
    model: ""
use_template: true
need_auditor: false
